config/routes.rb
Rails.application.routes.draw do
  get 'admin/menu'

  get 'admin/assessments'

  post 'assessment/new'

  get 'assessment/edit'

  get 'assessment/apply'

  get 'assessment/:id/apply' => 'assessment#application', as: :apply

  get 'assessment/:id/download.csv' => 'assessment#download', as: :download

  post 'assessment/save'

  get 'assessments' => 'assessment#menu'

  get 'nurses' => 'nurses#menu'

  get 'nurses/assessments'

  get 'users/new'

  get 'admin' => 'admin#menu'

  get 'admin/assessments'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'home' => 'welcome#home'

  get 'search' => 'welcome#search'

  get 'about' => 'welcome#about'

  root 'welcome#home'

end

app/views/admin/assessments.html.erb
<!DOCTYPE html>
<html>
<header>
  <link href="">
</header>
<%= render 'layouts/header' %>
<body>

  <div class="container">
    <div class="row">

      <h1 class="text-center">Assign Assessment</h1>

      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= form_for(:session, url: assessment_new_path) do |f| %>
          <div class="row">
            <div class="col-lg-6">
                <%= f.text_field :name, class: 'form-control', placeholder: "Insert assessment name"%>
            </div>
            <div class="col-lg-6">
              <div class="input-group">
                <%= f.email_field :email, class: 'form-control', placeholder: "Insert nurse email"%>
                <div class="input-group-btn">
                  <%= f.submit "Select", class: "btn btn-success" %>
                </div>
              </div>
            </div><!-- /.col-lg-6 -->
          </div><!-- /.row -->
      <% end %>
    </div>
    <div class="row">
      <div class="panel panel-default" style="margin: 12px">
        <div class="panel-heading">Available Nurses</div>

        <table class="table">
          <thead>
            <th>Name</th>
            <th>Email</th>
          </thead>
          <tbody>
            <% @users.each do |user| %>
                <tr>
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                </tr>
            <% end %>
        </table>
      </div>

    </div>
  </div>


</body>
</html>

app/views/admin/menu.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/header' %>
<body>

  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  </div>

</body>
</html>