config/routes.rb
Rails.application.routes.draw do
  get 'admin/menu'

  get 'admin/assessments'

  post 'assessment/new'

  get 'assessment/edit'

  get 'assessment/apply'

  get 'assessment/:id/apply' => 'assessment#application', as: :apply

  get 'assessment/:id/download.csv' => 'assessment#download', as: :download

  post 'assessment/save'

  get 'assessments' => 'assessment#menu'

  get 'nurses' => 'nurses#menu'

  get 'nurses/assessments'

  get 'users/new'

  get 'admin' => 'admin#menu'

  get 'admin/assessments'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'home' => 'welcome#home'

  get 'search' => 'welcome#search'

  get 'about' => 'welcome#about'

  root 'welcome#home'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home

  end

  def search
    @assessments = Assessment.all
    render :search
  end

  def login
    flash[:info] = 'Insert your email and password'
  end

  def about

  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/header' %>
<body>
  <h1 class="text-center">This is a demo! This feature is not implemened yet :)</h1>
</body>
</html>

app/views/welcome/home.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/header' %>
  <body>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox" align="center">
      <div class="item active">
        <img class="testes" src="http://likefotos.com/wp-content/uploads/2015/01/paisagem-tailandia1.jpg" alt="1">
      </div>

      <div class="item">
        <img class="testes" src="http://likefotos.com/wp-content/uploads/2015/01/paisagem-tailandia1.jpg" alt="2">
      </div>

      <div class="item">
        <img class="testes" src="http://likefotos.com/wp-content/uploads/2015/01/paisagem-tailandia1.jpg" alt="3">
      </div>


  </div>


    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  </body>
</html>

app/views/welcome/login.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/header' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">Login</div>
      <div class="panel-body">
        <div class="input-group">
          <span class="input-group-addon" id="email-addon"></span>
          <input type="email" class="form-control" placeholder="Email" aria-describedby="email-addon" id="email">
        </div>
        <h4></h4>
        <div class="input-group">
          <span class="input-group-addon" id="password-addon"></span>
          <input type="password" class="form-control" placeholder="Password" aria-describedby="password-addon" id="password">
        </div>
        <h4></h4>
        <button type="button" class="btn btn-success" aria-label="Right Align">
          <span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"></span>
        </button>
      </div>
    </div>
  </div>
</div>

</html>

app/views/welcome/search.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/header' %>
<body>
  <div class="container">

    <div class="row">
      <div class="panel panel-default" style="margin: 12px">
        <div class="panel-heading">Available Assessments <%=  %> </div>
          <table class="table">
            <thead>
            <th>Name</th>
            <th>Date of Creation</th>
            <th>Download</th>
            </thead>
            <tbody>
            <% @assessments.each do |a| %>
                <tr>
                  <td><%= a.name %></td>
                  <td><%= a.created_at.strftime("%b %d, %Y") %></td>
                  <td>
                    <%= link_to image_tag('csv.png'), download_path(a.id) %>
                  </td>
                </tr>
            <% end %>
          </table>
        </div>
      </div>
    <div class="text-right">Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
    </div>
  </div>
</body>
</html>