config/routes.rb
Rails.application.routes.draw do
  get 'admin/menu'

  get 'admin/assessments'

  post 'assessment/new'

  get 'assessment/edit'

  get 'assessment/apply'

  get 'assessment/:id/apply' => 'assessment#application', as: :apply

  get 'assessment/:id/download.csv' => 'assessment#download', as: :download

  post 'assessment/save'

  get 'assessments' => 'assessment#menu'

  get 'nurses' => 'nurses#menu'

  get 'nurses/assessments'

  get 'users/new'

  get 'admin' => 'admin#menu'

  get 'admin/assessments'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'home' => 'welcome#home'

  get 'search' => 'welcome#search'

  get 'about' => 'welcome#about'

  root 'welcome#home'

end

app/views/layouts/_admin_jumbatron_menu_options.erb
<ul class="nav nav-pills" role="tablist">
  <li role="presentation"><%= link_to "Browse", about_path, id: "browse" %></li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Dropdown <span class="caret"></span>
    </a>
  <ul class="dropdown-menu">
    <li role="presentation"><%= link_to "Assessments", admin_assessments_path, id: "assessment" %></li>
  </ul>

</ul>

app/views/layouts/_assessment_cultural.html.erb
<ul class="nav nav-pills" role="tablist">
  <li role="presentation"><%= link_to "Health Assessment", about_path, id: "healthAssessment" %></li>
  <li role="presentation"><%= link_to "Save", about_path, id: "save" %></li>
  <li role="presentation"><%= link_to "Cancel", about_path, id: "cancel" %></li>
</ul>

app/views/layouts/_assessment_health.html.erb
<ul class="nav nav-pills" role="tablist">
  <li role="presentation"><%= link_to "Cultural Assessment", about_path, id: "culturalAssessment" %></li>
  <li role="presentation"><%= link_to "Save", about_path, id: "save" %></li>
  <li role="presentation"><%= link_to "Cancel", about_path, id: "cancel" %></li>
</ul>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top menu" style="margin: 0px ">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <!--<div id="logo"><a id="" class="navbar-brand" href="<%=home_path%>"></a></div>-->
      <a id="" class="navbar-brand title" href="<%=home_path%>">Cultural & Health Assessment</a>

    </div>



    <div class="collapse navbar-collapse" id="navbar-collapse-1" >
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "About", about_path, id: "about" %></li>
        <li><%= link_to "Search", search_path, id: "search" %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <% if logged_admin? %>
                <li role="presentation" class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    Assessment <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li role="presentation"><%= link_to "Assign", admin_assessments_path, id: "assign" %></li>
                    <li role="presentation"><%= link_to "Create", about_path, id: "create" %></li>
                    <li role="presentation"><%= link_to "Edit", about_path, id: "edit" %></li>
                  </ul>
                </li>
            <%else%>
                <li role="presentation" class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    Assessment <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li role="presentation"><%= link_to "Select", assessment_apply_path, id: "select" %></li>
                    <li role="presentation"><%= link_to "Edit", about_path, id: "edit" %></li>
                  </ul>
                </li>
            <%end%>
            <li><%= link_to "Logout", logout_path, id: "logout", method: "delete"%></li>
        <%else%>
            <li><%= link_to "Login", login_path, id: "login" %></li>
        <%end%>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_main_jumbotron.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-md-6">
      <h1><%= @title %></h1>
    </div>
    <div class="col-md-6">
      <% if @page == 'nurse_menu' %>
        <%= render 'layouts/nurse_jumbatron_menu_options' %>
      <% end %>
      <% if @page == 'admin_menu' %>
          <%= render 'layouts/admin_jumbatron_menu_options' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_nurse_jumbatron_assessment.html.erb
asdasdsa

app/views/layouts/_nurse_jumbatron_menu_options.html.erb
<ul class="nav nav-pills" role="tablist">
  <li role="presentation"><%= link_to "Browse", about_path, id: "browse" %></li>
  <li role="presentation"><%= link_to "Assessments", nurses_assessments_path, id: "assessment" %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthAssessment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>